(eval-when (:compile-toplevel :load-toplevel :execute)
  (load "test-util")
  (load "../bounded-partition-number.lisp"))

(use-package :test-util)

(with-test (:name make-bpartition)
  (let ((table (make-bpartition 1 0 100000)))
    (assert (= 1 (aref table 0 0)))
    (assert (equal '(1 1) (array-dimensions table))))
  (let ((table (make-bpartition 361 25 100000)))
    (assert (= 74501 (aref table 360 25)))
    (assert (= (aref table 3 3) (aref table 3 4) (aref table 3 5)))
    (assert (= 0 (aref table 3 0)))
    (assert (= 1 (aref table 0 0)))
    (assert (= 1 (aref table 0 1)))))
