(eval-when (:compile-toplevel :load-toplevel :execute)
  (load "test-util")
  (load "../dfs-order.lisp"))

(use-package :test-util)

(with-test (:name make-dfs-order)
  (multiple-value-bind (pre post)
      (make-dfs-order #((1.1 2.1) (3.1) (4.1) () ()) :key #'round)
    (assert (equalp pre #(0 1 5 2 6)))
    (assert (equalp post #(9 4 8 3 7))))
  (multiple-value-bind (pre post)
      (make-dfs-order #((1 2) (0 3) (0 4) (1) (2)) :root 1)
    (assert (equalp pre #(1 0 2 7 3)))
    (assert (equalp post #(6 9 5 8 4))))
  (assert (equalp '(#() #())
                  (multiple-value-list (make-dfs-order #())))))
