(eval-when (:compile-toplevel :load-toplevel :execute)
  (load "test-util")
  (load "../find-argopt.lisp"))

(use-package :test-util)

(defun find-argopt* (sequence predicate &key start end (key #'identity))
  (multiple-value-list (find-argopt sequence predicate :start start :end end :key key)))

(defun coerce-to-hash-table (alist)
  (let ((table (make-hash-table)))
    (loop for (key . value) in alist
          do (setf (gethash key table) value))
    table))

(with-test (:name find-argopt)
  ;; list
  (let ((lst '(3 2 3 4 5 2)))
    (assert (equalp '(1 2) (find-argopt* lst #'<)))
    (assert (equalp '(5 2) (find-argopt* lst #'<=)))
    (assert (equalp '(4 5) (find-argopt* lst #'>)))
    (assert (equalp '(5 2) (find-argopt* lst #'< :start 3)))
    (assert (equalp '(1 2) (find-argopt* lst #'< :start 1)))
    (assert (equalp '(1 2) (find-argopt* lst #'< :start 1 :end 4)))
    (assert (equalp '(5 2) (find-argopt* lst #'< :start 3)))
    (assert (equalp '(0 3) (find-argopt* lst #'< :end 1)))
    (assert (equalp '(1 2) (find-argopt* lst #'< :key #'1+)))
    (assert (equalp '(4 5) (find-argopt* lst #'< :key #'-)))
    (signals error (find-argopt* lst #'< :end 0))
    (signals error (find-argopt* lst #'< :start 7))
    (signals error (find-argopt* '() #'<)))
  ;; vector
  (let ((vec #(3 2 3 4 5 2)))
    (assert (equalp '(1 2) (find-argopt* vec #'<)))
    (assert (equalp '(5 2) (find-argopt* vec #'<=)))
    (assert (equalp '(4 5) (find-argopt* vec #'>)))
    (assert (equalp '(5 2) (find-argopt* vec #'< :start 3)))
    (assert (equalp '(1 2) (find-argopt* vec #'< :start 1)))
    (assert (equalp '(1 2) (find-argopt* vec #'< :start 1 :end 4)))
    (assert (equalp '(5 2) (find-argopt* vec #'< :start 3)))
    (assert (equalp '(0 3) (find-argopt* vec #'< :end 1)))
    (assert (equalp '(1 2) (find-argopt* vec #'< :key #'1+)))
    (assert (equalp '(4 5) (find-argopt* vec #'< :key #'-)))
    (signals error (find-argopt* vec #'< :end 0))
    (signals error (find-argopt* vec #'< :start 7))
    (signals error (find-argopt* #() #'<)))
  ;; hash-table
  (let ((table (coerce-to-hash-table '((#\a . 3) (#\b . 2) (#\c . 3) (#\d . 4) (#\e . 5) (#\f . 2)))))
    (assert (equalp '(#\b 2) (find-argopt* table #'<)))
    (assert (equalp '(#\f 2) (find-argopt* table #'<=)))
    (assert (equalp '(#\e 5) (find-argopt* table #'>)))
    (assert (equalp '(#\b 2) (find-argopt* table #'< :key #'1+)))
    (assert (equalp '(#\e 5) (find-argopt* table #'< :key #'-)))
    (signals error (find-argopt* table #'< :end 0))
    (signals error (find-argopt* table #'< :start 7))
    (signals error (find-argopt* '() #'<))))
