(eval-when (:compile-toplevel :load-toplevel :execute)
  (load "test-util")
  (load "../lca.lisp"))

(use-package :test-util)

(with-test (:name lca)
  (let* ((graph (make-array 8 :element-type 'list :initial-contents '((1 2) (0 3 4) (0 5) (1) (1 6 7) (2) (4) (4))))
         (graph2 (make-array 9 :element-type 'list :initial-contents '((1) (0 2) (1 3) (2 4) (3 5) (4 6) (5 7) (6 8) (7))))
         (table (make-lca-table graph :root 0))
         (table2 (make-lca-table graph2)))
    (assert (= 4 (get-lca 6 7 table)))
    (assert (= 1 (get-lca 3 7 table)))
    (assert (= 0 (get-lca 3 5 table)))
    (assert (= 0 (get-lca 5 3 table)))
    (assert (= 4 (get-lca 4 4 table)))
    (assert (= 5 (distance-on-tree 7 5 table)))
    (assert (= 0 (distance-on-tree 4 4 table)))
    (assert (= 1 (distance-on-tree 3 1 table)))
    (dotimes (u 9)
      (dotimes (v 9)
        (assert (= (min u v) (get-lca u v table2))))))
  ;; forest
  (let ((table (make-lca-table #((3) () (6) (7 0 9) (7) () (2) (4 3) () (3)))))
    (assert (equalp #(0 0 0 1 3 0 1 2 0 2) (lca-depths table)))
    (signals two-vertices-disconnected-error (get-lca 0 1 table))
    (signals two-vertices-disconnected-error (distance-on-tree 1 2 table))))
