(eval-when (:compile-toplevel :load-toplevel :execute)
  (load "test-util")
  (load "../next-permutation.lisp")
  (load "../map-permutations.lisp")
  (load "./set-equal.lisp"))

(use-package :test-util)

(with-test (:name next-permutation)
  (signals no-permutation-error (next-permutation! #()))
  (signals no-permutation-error (next-permutation! #(#\a) :order #'char<))
  (assert (equalp #(#\b #\a) (next-permutation! #(#\a #\b) :order #'char<)))
  (signals no-permutation-error (next-permutation! #(#\b #\a) :order #'char<))
  (let (perms1 perms2)
    (let ((seq (vector #\a #\b #\c #\d #\e #\f)))
      (dotimes (i 720)
        (push (copy-seq seq) perms1)
        (when (< i 719) (next-permutation! seq :order #'char<))))
    (let ((seq (vector #\a #\b #\c #\d #\e #\f)))
      (do-permutations! (perm seq)
        (push (copy-seq perm) perms2)))
    (assert (set-equal perms1 perms2 :test #'equalp))))
