(eval-when (:compile-toplevel :load-toplevel :execute)
  (load "test-util")
  (load "../with-cache.lisp"))

(use-package :test-util)

(with-test (:name with-cache)
  ;; array
  (let (call-stack)
    (with-cache (:array (3 3) :initial-element -1)
      (labels ((add (x y)
                 (push (cons x y) call-stack)
                 (if (zerop x)
                     y
                     (+ 1 (add (- x 1) y)))))
        (assert (= 3 (add 1 2)))
        (assert (equal '((1 . 2) (0 . 2)) (reverse call-stack)))
        (setq call-stack nil)
        (assert (= 4 (add 2 2)))
        (assert (equal '((2 . 2)) (reverse call-stack)))
        (setq call-stack nil)
        (assert (= 3 (add 1 2)))
        (assert (null (reverse call-stack))))))
  ;; hash-table
  (let (call-stack)
    (with-cache (:hash-table :test #'equal)
      (labels ((add (x y)
                 (push (cons x y) call-stack)
                 (if (zerop x)
                     y
                     (+ 1 (add (- x 1) y)))))
        (assert (= 3 (add 1 2)))
        (assert (equal '((1 . 2) (0 . 2)) (reverse call-stack)))
        (setq call-stack nil)
        (assert (= 4 (add 2 2)))
        (assert (equal '((2 . 2)) (reverse call-stack)))
        (setq call-stack nil)
        (assert (= 3 (add 1 2)))
        (assert (null (reverse call-stack)))))))
