(defun parse-decimal (simple-base-string &key (start 0) end)
  "Is a variant of SBCL(x64)'s PARSE-INTEGER, specialized for decimal."
  (declare (optimize (speed 3)))
  (sb-c::with-array-data ((string simple-base-string :offset-var offset)
                          (start start)
                          (end end)
                          :check-fill-pointer t)
    (let ((index (do ((i start (1+ i)))
                     ((= i end)
                      (return-from parse-decimal (values nil end)))
                   (declare (fixnum i))
                   (unless (char= #\Space (schar string i)) (return i))))
          (minusp nil)
          (result 0))
      (declare (fixnum index)
               (integer result))
      (let ((char (schar string index)))
        (cond ((char= char #\-)
               (setq minusp t)
               (incf index))
              ((char= char #\+)
               (incf index))))
      (loop
        (when (= index end) (return nil))
        (let* ((char (schar string index))
               (weight (- (char-code char) 48)))
          (if (<= 0 weight 9)
              (setq result (+ weight (* result 10)))
              (return nil)))
        (incf index))
      (values
       (if minusp (- result) result)
       (- index offset)))))
