(declaim (inline warshall-floyd!))
(defun warshall-floyd! (matrix)
  (let ((n (array-dimension matrix 0)))
    (dotimes (k n)
      (let ((base-k (array-row-major-index matrix k 0)))
        (dotimes (i n)
          (let ((base-i (array-row-major-index matrix i 0)))
            (dotimes (j n)
              (setf (row-major-aref matrix (+ base-i j))
                    (min (row-major-aref matrix (+ base-i j))
                         (+ (row-major-aref matrix (+ base-i k))
                            (row-major-aref matrix (+ base-k j)))))))))))
  matrix)
