(defpackage :cp/test/complex-geometry
  (:use :cl :fiveam :cp/complex-geometry)
  (:import-from :cp/test/base #:base-suite))
(in-package :cp/test/complex-geometry)
(in-suite base-suite)

(test cross*
  (is (= 0 (cross* #c(1 3) #c(2 6))))
  (is (= -6 (cross* #c(5 7) #c(13 17)))))

(test inside-convex-polygon-p
  (let ((tri #(#c(0 0) #c(2 0) #c(0 3))))
    (is (inside-convex-polygon-p #c(1 1) tri))
    (is (not (inside-convex-polygon-p #c(1 2) tri)))
    (is (not (inside-convex-polygon-p #c(0 0) tri)))
    (is (not (inside-convex-polygon-p #c(2 0) tri)))
    (is (not (inside-convex-polygon-p #c(0 3) tri)))))

(test in-circle
  (let ((a #c(2 1))
        (b #c(0 5))
        (c #c(-1 2)))
    (dolist (p '(#c(-1 3)
                 #c(0 2) #c(0 3) #c(0 4)
                 #c(1 1) #c(1 2) #c(1 3) #c(1 4) #c(1 5)
                 #c(2 2) #c(2 3) #c(2 4)
                 #c(3 3)))
      (is (> (in-circle a b c p) 0))
      (is (> (in-circle b a c p) 0)))
    (dolist (p '(#c(-1 2) #c(-1 4) #c(0 1) #c(0 5)
                 #c(2 1) #c(2 5)
                 #c(3 2) #c(3 4)))
      (is (= (in-circle a b c p) 0))
      (is (= (in-circle b a c p) 0)))
    (dolist (p '(#c(-2 2)
                 #c(-1 1) #c(-1 5) #c(0 0) #c(0 6)
                 #c(1 0) #c(1 6) #c(2 0) #c(2 6)
                 #c(3 1) #c(3 5)))
      (is (< (in-circle a b c p) 0))
      (is (< (in-circle b a c p) 0)))))

(test barycentric
  (let ((*random-state* (sb-ext:seed-random-state 0)))
    (labels ((rand ()
               (complex (- (random 2000) 1000) (- (random 2000) 1000) )))
      (dotimes (_ 100)
        (let ((a (rand))
              (b (rand))
              (c (rand))
              (p (rand)))
          (unless (zerop (cross* (- b a) (- c a)))
            (multiple-value-bind (u v w) (barycentric a b c p)
              (is (= p (+ (* u a) (* v b) (* w c)))))))))))
