(defpackage :cp/test/csc
  (:use :cl :fiveam :cp/csc :cp/matrix-rotate)
  (:import-from :cp/test/base #:base-suite)
  (:import-from :cp/csc #:csc-float #:+zero+))
(in-package :cp/test/csc)
(in-suite base-suite)

(test coo
  (let ((coo (make-coo 2 3)))
    (coo-insert! coo 0 0 1d0)
    (coo-insert! coo 10 20 1d0)
    (is (= 11 (coo-m coo)))
    (is (= 21 (coo-n coo)))
    (signals error (coo-insert! coo 100 200 1d0 t))))

(test csc/constructor
  (let ((*test-dribble* nil))
    (dotimes (m 10)
      (dotimes (n 10)
        (dolist (rate '(0d0 0.2d0 0.4d0 0.6d0 0.8d0 1d0))
          (let ((mat (make-array (list m n)
                                 :element-type 'csc-float
                                 :initial-element +zero+)))
            (dotimes (i m)
              (dotimes (j n)
                (when (< (random 1d0) rate)
                  (setf (aref mat i j) (- (random 100d0) 50d0)))))
            (let ((csc (make-csc-from-array mat)))
              (is (equalp (csc-to-array csc) mat))
              (is (equalp (csc-to-array (csc-transpose csc))
                          (matrix-transpose mat)))))
          (let ((mat (make-array (list m n) :element-type 'csc-float))
                (count (round (* rate m n)))
                (coo (make-coo m n)))
            (when (and (> m 0) (> n 0))
              (dotimes (_ count)
                (let ((i (random m))
                      (j (random n))
                      (value (- (random 100d0) 50d0)))
                  (setf (aref mat i j) value)
                  (coo-insert! coo i j value))))
            (let ((csc (make-csc-from-coo coo))
                  (csc2 (make-csc-from-array mat)))
              (is (equalp csc csc2)))))))))
