(defpackage :cp/test/log-ceil
  (:use :cl :fiveam :cp/log-ceil)
  (:import-from :cp/test/base #:base-suite))
(in-package :cp/test/log-ceil)
(in-suite base-suite)

(test log2-ceil
  (declare (notinline log2-ceil))
  (assert (= 0 (log2-ceil 0)))
  (assert (= 0 (log2-ceil 1)))
  (assert (= 1 (log2-ceil 1.5d0)))
  (assert (= 1 (log2-ceil 2)))
  (assert (= 2 (log2-ceil 2.1)))
  (assert (= 2 (log2-ceil 5/2)))
  (assert (= 2 (log2-ceil 4))))

(test log-ceil
  (declare (notinline log-ceil))
  (assert (= 0 (log-ceil 0 2)))
  (assert (= 0 (log-ceil 1 2)))
  (assert (= 1 (log-ceil 1.5d0 2)))
  (assert (= 1 (log-ceil 2 2)))
  (assert (= 2 (log-ceil 2.1 2)))
  (assert (= 2 (log-ceil 5/2 2)))
  (assert (= 2 (log-ceil 4 2)))
  (signals type-error (log-ceil 4 2.1))
  (assert (= 0 (log-ceil 0 3)))
  (assert (= 0 (log-ceil 1 3)))
  (assert (= 1 (log-ceil 1.5d0 3)))
  (assert (= 1 (log-ceil 3 3)))
  (assert (= 2 (log-ceil 3.1 3)))
  (assert (= 2 (log-ceil 7/2 3)))
  (assert (= 3 (log-ceil 27 3))))
