(eval-when (:compile-toplevel :load-toplevel :execute)
  (load "test-util")
  (load "../trie.lisp"))

(use-package :test-util)

(with-test (:name trie)
  (let ((trie (make-trie)))
    (trie-add! trie "abra")
    (trie-add! trie "abrac")
    (trie-add! trie "rac")
    (trie-add! trie "racad")
    (assert (= 1 (trie-get trie "abra")))
    (assert (= 2 (trie-get trie "abra" :target :prefix)))
    (assert (= 0 (trie-get trie "ab")))
    (assert (= 2 (trie-get trie "ab" :target :prefix)))
    (assert (= 0 (trie-get trie "")))
    (assert (= 4 (trie-get trie "" :target :prefix)))
    (trie-add! trie "")
    (assert (= 1 (trie-get trie "")))
    (assert (= 5 (trie-get trie "" :target :prefix)))
    (assert (= 0 (trie-get trie "abracada")))))
