name: CI

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
  test:
    name: ${{ matrix.lisp }}
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        lisp: [sbcl-bin/2.1.6, sbcl-bin/2.0.3, sbcl-bin/1.3.13, sbcl-bin/1.3.1]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Install ASDF
        run: |
          mkdir ~/common-lisp
          git clone --depth 1 -b 3.3.5.3 https://gitlab.common-lisp.net/asdf/asdf.git ~/common-lisp/asdf
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
      - name: Install fiveam
        run: ros install fiveam
      - name: Run tests
        run: |
          ros -s fiveam -e '(sb-ext:disable-debugger)
                            (ql:quickload :cp/test)
                            (or (fiveam:run! (quote cp/test/base:base-suite))
                                (uiop:quit 1))'
